compare3d:

  Pose3DReal:
    Server: 2 # 0 -> Deactivate, 1 -> Ice , 2 -> ROS
    Proxy: "Pose3D:default -h localhost -p 9001"
    Topic: "/odom"
    Name: comparePose3dReal

  Pose3DEstimated:
    Server: 2 # 0 -> Deactivate, 1 -> Ice , 2 -> ROS
    Proxy: "Pose3D:default -h localhost -p 8998"
    Topic: "/visual_slam/pose"
    Name: comparePose3dEstimated

  numMarker:
    Server: 2 # 0 -> Deactivate, 1 -> Ice , 2 -> ROS
    Proxy: "No proxy"
    Topic: "/visual_slam/numMarker"
    Name: comparePose3dEstimated
  NodeName: compare3d
