compare3d:

  Pose3DReal:
    Server: 2 # 0 -> Deactivate, 1 -> Ice , 2 -> ROS
    Proxy: "Pose3D:default -h localhost -p 9000"
    Topic: "//turtlebotROS/odom"
    Name: comparePose3dReal

  Pose3DEstimated:
    Server: 1 # 0 -> Deactivate, 1 -> Ice , 2 -> ROS
    Proxy: "Pose3D:default -h localhost -p 8998"
    Topic: "/slam_markers/pose"
    Name: comparePose3dEstimated

  NodeName: compare3d
